name: Deploy React Example to GitHub Pages

on:
  push:
    branches: [ demo-page ]
    paths:
      - 'examples/react/**'
      - '.github/workflows/deploy-example.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: examples/react/package-lock.json
          
      - name: Install dependencies
        run: |
          cd examples/react
          npm ci
          
      - name: Build React app
        run: |
          cd examples/react
          npm run build
        env:
          CI: false
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: examples/react/dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
